version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    env_file:
      - .env

  mentiongenerator:
    build:
      context: mention-generator/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - kafka

  crawler:
    build:
      context: crawler/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - kafka

  solr:
    image: solr:7.6
    ports:
      - "8983:8983"

  mentionstorer:
    build:
      context: mention-storer/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - kafka
      - solr

  mentionapi:
    build:
      context: mention-api/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - solr

  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  queryapi:
    build:
      context: query-api/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis